# Generated by Django 5.0.1 on 2024-02-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='state',
            field=models.CharField(default='Tamilnadu', max_length=100),
        ),
    ]
