# Generated by Django 5.0.1 on 2024-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrecord_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='is_super_admin',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='pincode',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Super_admin'), (2, 'Sub_admin'), (3, 'Worker'), (4, 'Customer')], default=1),
        ),
    ]
