# Generated by Django 3.2.23 on 2024-02-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userrecord_is_super_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadmins',
            name='company_district',
        ),
        migrations.RemoveField(
            model_name='subadmins',
            name='company_pincode',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='username',
        ),
        migrations.AlterField(
            model_name='subadmins',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='users.userrecord'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Super_admin'), (2, 'Sub_admin'), (3, 'Worker'), (4, 'Customer')], default=4),
        ),
    ]
