# Generated by Django 3.2.23 on 2024-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240202_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
