# Generated by Django 3.2.23 on 2024-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240202_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmins',
            name='comapany_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
