# Generated by Django 3.2.23 on 2024-02-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240202_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='subadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subadmins'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='state',
            field=models.CharField(blank=True, default='Tamilnadu', max_length=100, null=True),
        ),
    ]
