# Generated by Django 3.2.23 on 2024-02-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240202_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('problem_discription', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subadmins')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 4}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrecord')),
                ('tagged_worker', models.ForeignKey(blank=True, limit_choices_to={'user_type': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_to', to='users.userrecord')),
            ],
        ),
    ]
