# Generated by Django 3.2.23 on 2024-02-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240202_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subadmins',
            old_name='comapany_area',
            new_name='company_area',
        ),
        migrations.RenameField(
            model_name='subadmins',
            old_name='comapany_image',
            new_name='company_image',
        ),
    ]
