# Generated by Django 3.2.23 on 2024-02-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240202_2342'),
        ('users', '0012_problem'),
    ]

    operations = [
    ]
