# Generated by Django 3.2.23 on 2024-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20240203_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '9:00 AM - 11:00 AM'), (2, '11:00 AM - 1:00 PM'), (3, '1:00 PM - 3:00 PM'), (4, '3:00 PM - 5:00 PM'), (5, '5:00 PM - 7:00 PM'), (6, '7:00 PM - 9:00 PM')], default=None, null=True),
        ),
    ]
